-- V1: 초기 스키마 생성

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider    VARCHAR(20)  NOT NULL,
    provider_id VARCHAR(255) NOT NULL,
    nickname    VARCHAR(255) NOT NULL,
    profile_image_url VARCHAR(1024),
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_provider UNIQUE (provider, provider_id)
);

CREATE TABLE split_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id    BIGINT       NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    total_price  INT          NOT NULL,
    total_qty    INT          NOT NULL,
    split_count  INT          NOT NULL,
    image_url    VARCHAR(1024),
    latitude     DOUBLE PRECISION NOT NULL,
    longitude    DOUBLE PRECISION NOT NULL,
    address      VARCHAR(500) NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'WAITING',
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_split_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE INDEX idx_split_status ON split_requests (status);
CREATE INDEX idx_split_author ON split_requests (author_id);
CREATE INDEX idx_split_location ON split_requests (latitude, longitude);

CREATE TABLE split_participants (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_request_id BIGINT    NOT NULL,
    user_id          BIGINT    NOT NULL,
    joined_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_participant_split FOREIGN KEY (split_request_id) REFERENCES split_requests (id),
    CONSTRAINT fk_participant_user  FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_participant UNIQUE (split_request_id, user_id)
);
