-- V8: 반띵 채팅 (split 단위 그룹 채팅) — H2·PostgreSQL 공용 plain 컬럼
-- 방은 split 과 1:1 이라 별도 room 테이블 없이 split_id 를 방 키로 사용한다.

CREATE TABLE chat_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_id   BIGINT        NOT NULL,
    sender_id  BIGINT        NOT NULL,
    content    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_split  FOREIGN KEY (split_id)  REFERENCES split_requests (id),
    CONSTRAINT fk_chat_sender FOREIGN KEY (sender_id) REFERENCES users (id)
);
CREATE INDEX idx_chat_split_created ON chat_messages (split_id, created_at);

CREATE TABLE chat_read_states (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_id     BIGINT    NOT NULL,
    user_id      BIGINT    NOT NULL,
    last_read_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_chat_read       UNIQUE (split_id, user_id),
    CONSTRAINT fk_chatread_user   FOREIGN KEY (user_id) REFERENCES users (id)
);
